# C5 语句
## 5.1 try块和异常处理
例子：
```c++
try{
    func1();//throw 1;
    func2();//throw "error!";
    func3();//throw rumtime_error("error");
}
catch(int e){
    //
}
catch(const char * e){
    //
}
catch(rumtime_error e){
    //
}
```
程序执行流程：throw先抛出异常，将可能throw的函数放到try块里，接着根据throw的类型，catch相对应的类型。

注意：只要出现throw则立刻跳转到相应的catch，未执行的try块语句不再执行。
```c++
catch(...){
    //
}
catch(...)//表示其余的异常情况。
```
